#!/usr/bin/env bash
##############################################################################
#
#  dailydir - copy files from memory card to disk into daily subfolders
#
#  Copy ORF files from Olympus camera card to D: drive using WSL:
#  1. make mount point in WSL: sudo mkdir /mnt/e
#  2. mount the memory card in WSL: sudo mount -t drvfs E: /mnt/e
#  3. run this script to copy files into subfolders <DST>/<year>/<yyyy-mm-dd>
#  4. remove the memory card from WSL: sudo umount /mnt/e
#
#  (c) 2020 E. Dronkert
#  https://github.com/ednl
#
##############################################################################

SRC="/mnt/e/DCIM/101OLYMP"                 # location of original photo files
DST="/mnt/d/ewoud/Pictures/Olympus E520"   # destination base dir
EXT=".ORF"                                 # Olympus Raw Format files

[ ! -e "$SRC" ] || [ ! -d "$SRC" ] || [ ! -r "$SRC" ] && {
	echo "Not accessible: $SRC" >&2
	echo "Connect memory card: sudo mount -t drvfs E: /mnt/e" >&2
	exit 1
}

[ ! -e "$DST" ] || [ ! -d "$DST" ] || [ ! -w "$DST" ] && {
	echo "Not accessible: $DST" >&2
	exit 2
}

N=$(find "$SRC" -maxdepth 1 -type f -name '*'"$EXT" | wc -l)
[ -z "$N" ] || [ "$N" -lt 1 ] && {
	echo "No $EXT files found in $SRC" >&2
	exit 3
}

echo "Files found: $N"
echo

for D1 in $(stat -c '%y' "$SRC/"*"$EXT" | cut -d' ' -f1 | sort | uniq)
do
	D2=$(date -d "$D1 +1 day" +%Y-%m-%d)   # the next day as boundary
	Y=${D1%%-*}                            # the year as main subfolder
	SUB="$DST/$Y/$D1"                      # destination base dir + sub-sub-folder
	[ ! -e "$SUB" ] && mkdir -p "$SUB"     # create subfolder if not exists
	[ ! -e "$SUB" ] || [ ! -d "$SUB" ] || [ ! -w "$SUB" ] && {
		echo "Not accessible: $SUB" >&2
		exit 4
	}
	echo "Copying to $SUB"                 # the current day subfolder
	find "$SRC" -maxdepth 1 -type f \
		-name '*'"$EXT" \
		-newermt "$D1" ! -newermt "$D2" \
		-print -execdir cp -n -t "$SUB" {} +
	echo
done
echo "Done. Disconnect memory card: sudo umount /mnt/e"
