#!/usr/bin/env bash

# Check for mpc
MPC=$(which mpc)
[ ! -x "$MPC" ] && echo "Can't find mpc." >&2 && exit 1

# Use cmdline parameter or MPD_HOST variable or "pi3"
HOST=${1:-$MPD_HOST}
HOST=${HOST:-'pi3'}

# Fip stream URL
FIP='http://aifae8cah8.lb.vip.cdn.dvmr.fr:80/fip-midfi.mp3'

# Save current track, stop playing
CUR=$($MPC -h "$HOST" -f "%file%" current)
[ -n "$CUR" ] && $MPC -h "$HOST" stop &> /dev/null

# Start Fip if it wasn't playing
if [[ "$CUR" != "$FIP" ]]; then
    $MPC -h "$HOST" clear &> /dev/null
    $MPC -h "$HOST" add "$FIP" &> /dev/null
    $MPC -h "$HOST" play &> /dev/null
    # Display volume
    $MPC -h "$HOST" volume
fi
exit 0
