#!/usr/bin/env bash

# Check for mpc
[ ! -x "$(which mpc)" ] && echo 'Program "mpc" not found.' >&2 && exit 1

# Use first cmdline parameter or MPD_HOST variable or "black"
HOST=${1:-$MPD_HOST}
HOST=${HOST:-'black'}

# Check which host should be contacted, display if not localhost
THISHOST=$(hostname -s)
[ "$HOST" = "$THISHOST" -o "$HOST" = 'me' -o "$HOST" = 'this' ] && HOST='localhost'
[ "$HOST" != 'localhost' ] && echo -n "Host \"$HOST\" "

# Fip stream URL
FIP='http://chai5she.cdn.dvmr.fr/fip-midfi.mp3'

# Save current track, stop playing
CUR=$(mpc -h "$HOST" -f '%file%' current)
[ -n "$CUR" ] && mpc -h "$HOST" stop &> /dev/null

# Display status
echo -n 'Fip Radio '

# Start Fip if it wasn't playing before
if [ "$CUR" = "$FIP" ]; then
	# It was playing before but now it's off
	echo 'off'
else
	# Radio was off or playing something else
    mpc -h "$HOST" clear &> /dev/null
    mpc -h "$HOST" add "$FIP" &> /dev/null
    mpc -h "$HOST" play &> /dev/null
    # Display volume
    mpc -h "$HOST" volume
fi
exit 0
