#!/bin/bash

#######################################################################
# Made by    : Ewoud Dronkert
# Licence    : GNU GPL v3
# Platform   : Mac OS X
# Requires   : bash
# Location   : ~/bin/
# Name       : fittime
# Version    : 2.0.5
# Date       : 2016-07-21
# Purpose    : Align timestamp with file name for Garmin .fit files.
#              Also remove DOS 'execute' and OS X extended attributes.
# Parameters : none
# Settings   : FITDIR = location of Garmin Activity .fit files
# Exit     0 : No errors (but chmod/xattr/touch errors not monitored)
#          1 : FITDIR not found or not a directory
#          2 : No .fit files in FITDIR directory
#######################################################################

FITDIR=~/Documents/Garmin/Activities

if [ -d "$FITDIR" ]; then
	echo "Using directory : $FITDIR"
else
	echo "FIT-file directory not found: $FITDIR" 1>&2
	exit 1
fi

# Remove macOS extended attributes
xattr "$FITDIR"/*.fit | cut -d':' -f1 | sort | uniq | xargs xattr -c

# Change file mode to RW only for owner
find "$FITDIR"/*.fit -perm +177 | xargs chmod 600

# Exit early if no files found
tot=$(ls "$FITDIR"/*.fit | grep -E '\.fit$' | wc -l | grep -oE '\d+')
if (( tot >= 1 )); then
	echo "FIT-files found : $tot"
else
	echo "No FIT-files found." 1>&2
	exit 2
fi

# Set file modification time according to file name
err=0
adj=0
for f in "$FITDIR"/*.fit; do

	# File modification time in touch format
	m=$(stat -f '%Sm' -t '%Y%m%d%H%M.%S' "$f")

	# Faster than "basename $f"
	t=${f:(-23)}
	# Remove dashes
	t=${t//-/}
	# Format as YYYYMMDDhhmm.SS for touch
	t=${t:0:12}.${t:12:2}

	if [[ "$m" != "$t" ]]; then
		(( err++ ))
		touch -cfm -t $t "$f" && (( adj++ ))
	fi
done

echo "Wrong file time : $err"
echo "Time adjusted   : $adj"
exit 0
