#!/bin/bash

#######################################################################
# Made by    : Ewoud Dronkert
# Licence    : GNU GPL v3
# Platform   : Mac OS X
# Requires   : Bash, xattr
# Location   : ~/bin/
# Name       : googledrivetime
# Version    : 1.0.0
# Date       : 2016-02-08
# Purpose    : Align timestamps with file names for Motorola .jpg files
#            : synced via Google Drive.
#              Also remove DOS 'execute' and OS X extended attributes.
# Parameters : none
# Settings   : IMGDIR = location of latest Google Photos
# Exit     0 : No errors (but chmod/xattr/touch errors not monitored)
#          1 : IMGDIR not found or not a directory
#          2 : No .jpg files in IMGDIR directory
#######################################################################

# Only check the latest directory (organised by month), from current date
YEAR=$(date +"%Y")
MONTH=$(date +"%m")

# Dutch version of the Google Drive Photos directory name
IMGDIR=~/Google\ Drive/Google\ Foto\'s/$YEAR/$MONTH

if [ ! -d "$IMGDIR" ]; then
	echo "IMG-file directory not found: $IMGDIR" 1>&2
	exit 1
fi

# This file mask is valid for my Motorola phone. Only checks jpg files.
# You could modify the pattern to include videos.
FILEMASK="IMG_$YEAR$MONTH[0-3][0-9]_[0-2][0-9][0-5][0-9][0-5][0-9]*.jpg"

n=$(ls "$IMGDIR"/$FILEMASK | grep -E '\.jpg$' | wc -l | grep -oE '\d+')
if (( n >= 1 )); then
	echo "IMG-files found: $n"
else
	echo "No IMG-files found in directory: $IMGDIR" 1>&2
	exit 2
fi

m=0
for f in "$IMGDIR"/$FILEMASK; do
	b=$(basename "$f")
	# Get the part with date/time numbers
	t=${b:4:15}
	# Remove underscore
	t=${t/_/}
	# Format for 'touch'
	t=${t:0:12}.${t:12:2}
	chmod 600 "$f"
	xattr -c "$f"
	touch -t $t "$f" && (( m++ ))
	# Progress
	echo "$m/$n: $b"
done
exit 0
