#!/usr/bin/env bash
#######################################################################
# Made by    : Ewoud Dronkert
# Licence    : GNU GPL v3
# Platform   : macOS
# Requires   : bash, MacPorts, grep, awk, sed
# Location   : ~/bin/, /usr/local/bin
# Name       : macportsmissing
# Version    : 1.0.1
# Date       : 2020-10-27
# Purpose    : Check if all py38 packages also exist as py39
#######################################################################

SEARCH='py38'
REPLACE='py39'

echo "MacPorts packages installed for ${SEARCH}, missing for ${REPLACE}:"

PRESENT=0
MISSING=0

for NAME in $(port installed | grep -F "${SEARCH}" | awk '{print $1}' | sed "s/${SEARCH}/${REPLACE}/")
do

	# Search result will show package name at the start if found
	if port search "${NAME}" | grep -q "^${NAME}"; then
		(( PRESENT++ ))
	else
		(( MISSING++ ))
		echo "${NAME}"  # show missing package
	fi

done

echo
echo "Present: ${PRESENT}"
echo "Missing: ${MISSING}"
