#!/usr/bin/env bash

APP=wget
FOUND=$(which $APP)
[ -z "$FOUND" ] && { echo "Program not found: $APP" >&2; exit 1; }

DOCDIR=~/pico/docs
[ ! -d "$DOCDIR" ] && mkdir -p "$DOCDIR" && echo "Directory created: $DOCDIR"
[ ! -d "$DOCDIR" ] && { echo "Directory not found: $DOCDIR" >&2; exit 2; }

CURDIR=$(pwd)
BASE="https://datasheets.raspberrypi.org/"
EXT=".pdf"

cd "$DOCDIR"
for FNAME in \
	"pico/getting-started-with-pico" \
	"pico/raspberry-pi-pico-c-sdk" \
	"pico/pico-datasheet" \
	"pico/raspberry-pi-pico-python-sdk" \
	"pico/raspberry-pi-pico-faq" \
	"pico/Pico-R3-A4-Pinout" \
	"pico/pico-product-brief" \
	"rp2040/rp2040-datasheet" \
	"rp2040/hardware-design-with-rp2040"
do
	echo
	echo "     $(basename $FNAME)"
	echo
	$APP -N -nv --show-progress "$BASE$FNAME$EXT"
done
cd "$CURDIR"

echo
echo "Files saved to $DOCDIR"
echo
open "$DOCDIR"

exit 0
