#!/usr/bin/env bash

# Get homedir of user pi
DIR=$(cat /etc/passwd | grep -e '^pi:' | cut -d':' -f6)

RIP=$(which streamripper)
[ -z "$RIP" ] && echo "Install streamripper: sudo apt-get update && sudo apt-get install streamripper" && exit 1

MPC=$(which mpc)
[ -z "$MPC" ] && echo "Install mpc: sudo apt-get update && sudo apt-get install mpc" && exit 2

PID=$(pgrep streamripper)
if [ -z "$PID" ]; then
	URL=$($MPC --format %file% | grep http)
	if [ -n "$URL" ]; then
		REC=$(date '+%Y%m%d%H%M%S').mp3
		nohup $RIP "$URL" -d "$DIR" -s -a "$REC" -A -T --quiet &
		echo
		echo "    Now recording $URL ..."
		echo
	else
		echo
		echo "    No stream found, not recording."
		echo
	fi
else
	killall streamripper
	[ -e "$DIR/nohup.out" ] && rm "$DIR/nohup.out"
	for CUE in $DIR/*.cue; do
		if [ -e "$CUE" ]; then
			rm "$CUE"
		fi
	done
	echo
	echo "    Recording stopped. Today's recordings:"
	echo
	ls -l $DIR/$(date '+%Y%m%d')*.mp3
	echo
fi
