#!/usr/bin/env bash
#######################################################################
# Made by    : Ewoud Dronkert
# Licence    : GNU GPL v3
# Platform   : Mac OS X
# Requires   : Bash, dig
# Location   : ~/bin/
# Name       : uppi
# Version    : 1.0.0
# Date       : 2014-11-17
# Purpose    : Check which computers from a list are up on the LAN
#              Use dig to query local DNS (modem/router)
#              Print IPv4 addresses of computers that are up
#              List computers that are down
# Parameters : none
# Exit    0+ : number of computers that are down
#         10 : dig not found
#######################################################################

DIGBIN=/usr/bin/dig
REMOTEHOST='home dev black cam dac2'
DNSSERVER=192.168.178.1
DNSSUFFIX=.fritz.box

if [ ! -x $DIGBIN ]; then
	echo "Can't execute $DIGBIN" >&2
	exit 10
fi

OFF=
ERR=0
for RPI in $REMOTEHOST; do
	ADDR=$($DIGBIN @$DNSSERVER $RPI$DNSSUFFIX A +short)
	if [ -z "$ADDR" ]; then
		OFF="$OFF $RPI"
		(( ERR += 1 ))
	else
		echo "$RPI [$ADDR]"
	fi
done

[ -z "$OFF" ] || echo "Offline:$OFF" >&2
exit $ERR
