#!/usr/bin/env bash

#############################################################################
# Made by    : Ewoud Dronkert
# Licence    : GNU GPL v3
# Platform   : Mac OS X
# Requires   : bash
# Location   : ~/bin/
# Name       : wxcopy
# Version    : 1.0.1
# Date       : 2017-07-19
# Purpose    : Copy new photos from camera to disk into daily subfolders. Do
#              the same for existing photos in the main folder on disk.
#              Files are sorted lexicographically (A to Z, 0 to 9) and the
#              last ones on camera and disk are compared. So, not necessarily
#              a full inventory of every file on camera or disk.
# Parameters : none
# Settings   : DST = destination folder on disk
#              VOL = source volume (camera memory card mounted on disk)
#              SRC = source folder with camera JPEGs under VOL
# Exit     0 : No script errors but photos may not have been copied
#          1 : Destination folder not found or not a directory
#          2 : Destination folder not writeable
#          3 : Camera memory card not mounted
#          4 : JPEG folder not found on camera memory card
#          5 : No JPEGs found on camera memory card
#          6 : Photos on disk the same as on camera (lexicographically)
#          7 : Photos on disk newer than on camera (lexicographically)
#############################################################################

DST=~/Pictures/Camera\ Sony\ WX220
VOL=/Volumes/WX220
SRC="$VOL/DCIM/100MSDCF"

# Check destination folder
[ ! -d "$DST" ] && { echo "Destination folder not found: \"$DST\"" 1>&2; exit 1; }
[ ! -w "$DST" ] && { echo "Can't write to destination folder: \"$DST\"" 1>&2; exit 2; }

# Clean up destination base folder
echo -n 'Moving photos already on disk to daily subfolders ... '
NDIR=0
SUCC=0
FAIL=0
for FPATH in "$DST"/DSC*.JPG; do
	if [ -f "$FPATH" ]; then
		SUB=$(stat -q -f '%Sm' -t '%Y%m%d' "$FPATH")
		LEN=$(expr "${SUB}" : '[0-9]*')
		if [ "$LEN" -eq 8 ]; then
			[ ! -e "$DST/$SUB" ] && mkdir "$DST/$SUB" && (( ++NDIR ))
			if [ -d "$DST/$SUB" ]; then
				mv -f "$FPATH" "$DST/$SUB" && (( ++SUCC ))
				touch -t ${SUB}0000.00 "$DST/$SUB"
			else
				(( ++FAIL ))
			fi
		else
			(( ++FAIL ))
		fi
	fi
done
echo 'Done.'
(( NDIR > 0 )) && echo "    New subfolders created     : $NDIR"
(( SUCC > 0 )) && echo "    Photos moved to subfolders : $SUCC"
(( FAIL > 0 )) && echo "    Could not determine photo date, left in base folder : $FAIL"

# Check source volume
[ ! -d "$VOL" ] && { echo 'Camera "WX220" not mounted.' 1>&2; exit 3; }

# Check source folder
[ ! -d "$VOL" ] && { echo 'JPEG folder not found on camera.' 1>&2; exit 4; }

# Check photos on camera
TOT=$(ls "$SRC"/DSC*.JPG 2>/dev/null | wc -l | xargs)
[ "$TOT" -eq 0 ] && { echo 'No photos found on camera.' 1>&2; exit 5; }
echo "Number of photos on camera   : $TOT"
CAM=$(ls "$SRC"/DSC*.JPG 2>/dev/null | tail -n 1 | xargs basename)
echo "Newest photo found on camera : $CAM"

# Find newest photo by filename in destination subfolder
REF=
SUB=$(find -s "$DST" -depth 1 -type d | tail -n 1)
[ -d "$SUB" ] && REF=$(ls "$SUB"/DSC*.JPG | tail -n 1)
[ -n "$REF" ] && REF=$(basename "$REF")

# Or maybe newest photo in main folder
T=$(ls "$DST"/DSC*.JPG 2>/dev/null | tail -n 1)
[ "$T" \> "$REF" ] && REF="$T"

# Reference file
[ -n "$REF" ] && echo "Newest photo found on disk   : $REF"
[ "$CAM" = "$REF" ] && { echo "Photos on disk are the same as on camera."; exit 6; }
[ "$CAM" \< "$REF" ] && { echo "Photos on disk are newer than on camera."; exit 7; }

echo -n "Copying photos from camera to disk ... "
TRY=0
PREV=0
NDIR=0
CPSUB=0
CPBASE=0
SUCC=0
FAIL=0
PREV=0
for FPATH in "$SRC"/DSC*.JPG; do
	if [ -f "$FPATH" ]; then
		FNAME=$(basename "$FPATH")
		if [ "$FNAME" \> "$REF" ]; then
			(( ++TRY ))
			SUB=$(stat -q -f '%Sm' -t '%Y%m%d' "$FPATH")
			LEN=$(expr "${SUB}" : '[0-9]*')
			if [ "$LEN" -eq 8 ]; then
				[ ! -e "$DST/$SUB" ] && mkdir "$DST/$SUB" && (( ++NDIR ))
				if [ -d "$DST/$SUB" ]; then
					cp -fp "$FPATH" "$DST/$SUB" && (( ++CPSUB ))
					touch -t ${SUB}0000.00 "$DST/$SUB"
				else
					cp -fp "$FPATH" "$DST" && (( ++CPBASE ))
				fi
			else
				cp -fp "$FPATH" "$DST" && (( ++CPBASE ))
			fi
			(( SUCC = CPSUB + CPBASE ))
			(( FAIL = TRY - SUCC ))
			(( FAIL != PREV )) && echo -n "\n    FAILED: $FNAME "
			PREV=$FAIL
		fi
	fi
done
echo "Done."
(( NDIR > 0 ))   && echo "    New subfolders created for every day  : $NDIR"
(( SUCC > 0 ))   && echo "    Photos copied from camera to disk     : $SUCC"
(( CPSUB > 0 ))  && echo "        Photos copied to daily subfolders : $CPSUB"
(( CPBASE > 0 )) && echo "        Photos copied to base folder      : $CPBASE"
(( FAIL > 0 ))   && echo "    Photos NOT copied to disk             : $FAIL"

exit 0
