#!/usr/bin/env bash

M=/Volumes/
D1=T7Zwart
D2=T7Rood

checkvol () {
	[ -e "$M$1" -a -d "$M$1" -a -r "$M$1" -a -w "$M$1" ] || {
		echo "Disk not found or not accessible: $1" >&2
		exit 1
	}
	return 0
}

checkvol "$D1"
checkvol "$D2"

APP=rsync
BIN="$(which $APP)"
[ -z "$BIN" ] && { echo "Command not found: $APP" >&2; exit 2; }

F1=$(df -g "$M$D1" | tail -n1 | awk '{print $4}')
F2=$(df -g "$M$D2" | tail -n1 | awk '{print $4}')

echo "Free space on disk:"
echo
printf "   %-15s %5u GB\n" "$D1" "$F1"
printf "   %-15s %5u GB\n" "$D2" "$F2"

echo
IFS=
read -p "Completely synchronise disks $D1 and $D2? (y/N) " -n 1 -s -r
echo

if [[ "$REPLY" =~ ^[Yy]$ ]]
then
	ARG='-auv --exclude=.Spotlight-V100 --exclude=.Trashes --exclude=.fseventsd --exclude=.DS_Store'
	echo
	echo "   Synchronising from $D1 to $D2 ..."
	echo
	$APP $ARG "$M$D1/" "$M$D2/"
	echo
	echo "   Synchronising from $D2 to $D1 ..."
	echo
	$APP $ARG "$M$D2/" "$M$D1/"
fi
